title: Augustine Ooi # your name (or website title) here
logo: "/images/profilepic_data.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Investments (PE & VC) | Data Science | Data Analytics
  <br><br>
  - ModularMaster Data Science | Singapore University of Technology and Design
  - M. Sc. Eng. | The University of Melbourne
  <br><br>
  <a href="https://www.linkedin.com/in/augustineooi/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
