title: Augustine Ooi # your name (or website title) here
logo: "/images/aooi_profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Investment Professional transitioning into a Data Scientist role
  <br><br>
  ModularMaster Data Science, SUTD
  <br>
  M. Sc. Eng., The University of Melbourne
  <br>
  CFA Charterholder
  <br><br>
  
  <a href="https://www.linkedin.com/in/augustineooi/" class="social-icon si-rounded si-small si-linkedin">
  <i class="icon-linkedin"></i>
  </a>
  
  # <a href="https://www.linkedin.com/in/augustineooi/">LinkedIn</a> 
  # email: augustineooi@gmail.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
